feature_names = ['Rating', 'Founded', 'Size', 'Job Title_Analytics Manager/Consultant',
                 'Job Title_Business Intelligence Analyst',
                 'Job Title_Clinical Scientist', 'Job Title_Data Analyst',
                 'Job Title_Data Engineer', 'Job Title_Data Scientist',
                 'Job Title_Machine Learning Engineer',
                 'Job Title_Manager/Director in Data Field',
                 'Job Title_Research Scientist',
                 'Job Title_Software Engineer (Data Focus)',
                 'Job Title_Specialized Scientific Roles', 'Job Title_Statistician',
                 'Type of ownership_College / University',
                 'Type of ownership_Company - Private',
                 'Type of ownership_Company - Public', 'Type of ownership_Government',
                 'Type of ownership_Hospital',
                 'Type of ownership_Nonprofit Organization',
                 'Type of ownership_Other Organization',
                 'Type of ownership_Subsidiary or Business Segment',
                 'Industry_Aerospace & Defense', 'Industry_Biotech & Pharmaceuticals',
                 'Industry_Consulting', 'Industry_Education',
                 'Industry_Energy & Utilities', 'Industry_Financial Services',
                 'Industry_Health Care', 'Industry_Insurance',
                 'Industry_Logistics & Transportation', 'Industry_Manufacturing',
                 'Industry_Media & Entertainment', 'Industry_Others',
                 'Industry_Professional Services', 'Industry_Real Estate & Construction',
                 'Industry_Retail & Consumer Services', 'Industry_Technology',
                 'Industry_Travel Agencies']
